#!/bin/bash

# run all GAP benchmarks

cd BFS
numactl --interleave=all ./do_gap

cd ../BetweennessCentrality
numactl --interleave=all ./do_gap

cd ../CC
numactl --interleave=all ./do_gap

cd ../PageRank3
numactl --interleave=all ./do_gap

cd ../SSSP
numactl --interleave=all ./do_gap

cd ../TriangleCount
numactl --interleave=all ./do_gap

