# based on travis.yml from graphalytics
language: c
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.3
install:
  # GraphBLAS
  - git clone --depth 1 --branch v3.2.0 https://github.com/DrTimothyAldenDavis/GraphBLAS
  - cd GraphBLAS
  - JOBS=$(nproc) CFLAGS=-DGBCOMPACT make
  - sudo make install
  - if [ `command -v ldconfig` ]; then sudo ldconfig; fi
  - cd ..
  # LAGraph
  - git clone --depth 1 --branch ${TRAVIS_BRANCH} https://github.com/${TRAVIS_REPO_SLUG}
  - cd LAGraph
  - JOBS=$(nproc) make
  - sudo make install
  - if [ `command -v ldconfig` ]; then sudo ldconfig; fi
  - cd ..
script:
  - make tests
