# based on travis.yml from graphalytics
language: c
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.3
install:
  # clone GraphBLAS next to LAGraph's directory
  - pushd .
  - cd ..
  - git clone --depth 1 --branch v3.3.3 https://github.com/DrTimothyAldenDavis/GraphBLAS
  - cd GraphBLAS/build
  - cmake -DGBCOMPACT=1 -DCMAKE_C_FLAGS="$(CMAKE_C_FLAGS) -w" ..
  - JOBS=2 make
  - popd
script:
  # build and test LAGraph
  - cd build
  - cmake ..
  - JOBS=2 make
  - cd ..
  # drop BFS test which requires SuiteSparse:GraphBLAS 4.0+
  - sed -i.bkp '/( cd BFS                   ; $(MAKE) --jobs=$(JOBS) CC=$(CC) CXX=$(CC) )/d' Test/Makefile
  - make tests
