# based on travis.yml from graphalytics
language: c
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.3
      env:
        - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
install:
  # GraphBLAS
  - git clone --depth 1 --branch master https://github.com/DrTimothyAldenDavis/GraphBLAS
  - cd GraphBLAS/build
  - cmake -DGBCOMPACT=1 ..
  - JOBS=$(nproc) make
  - cd ../..
script:
  - git clone --depth 1 --branch ${TRAVIS_BRANCH} https://github.com/${TRAVIS_REPO_SLUG}
  - cd LAGraph/build
  - cmake ..
  - JOBS=$(nproc) make
  - cd ..
script:
  - make tests
