all:
	g++ -o gen_bipartite gen_bipartite.cpp
	g++ -o verify verify_matching.cpp

# For my Mac
local:
	g++-11 -o gen_bipartite gen_bipartite.cpp
	g++-11 -o verify verify_matching.cpp

clean:
	rm gen_bipartite
	rm verify
