all:
	g++ -o gen_general gen_general.cpp
	g++ -o gen_bipartite gen_bipartite_orig.cpp
	g++ -o verify verify_matching.cpp

# For my Mac
local:
	g++-11 -o gen_general gen_general.cpp
	g++-11 -o gen_bipartite gen_bipartite_orig.cpp
	g++-11 -o verify verify_matching.cpp

clean:
	rm gen_general
	rm gen_bipartite
	rm verify
