#!/bin/sh

./build/test_cc ~/GAP/GAP-kron/GAP-kron.grb
./build/test_cc ~/GAP/GAP-urand/GAP-urand.grb
./build/test_cc ~/GAP/GAP-twitter/GAP-twitter.grb
./build/test_cc ~/GAP/GAP-web/GAP-web.grb
./build/test_cc ~/GAP/GAP-road/GAP-road.grb

