#!/bin/bash

# run all GAP benchmarks (my2*)

cd BetweennessCentrality
qsub my2_BC_plat

cd ../BFS
qsub my2_BFS_plat

cd ../CC
qsub my2_CC_plat

cd ../PageRank3
qsub my2_PR_plat

cd ../SSSP
qsub my2_SSSP_plat

cd ../TriangleCount
qsub my2_TC_plat

