#!/bin/sh

#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 1  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 2  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 3  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 4  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 5  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 6  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 7  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 8  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 9  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 10  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 15  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 27  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb  44  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 50  /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
#./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 100 /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx 
