#!/bin/sh

./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 10  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 15  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 20  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 25  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 27  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 30  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 32  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 34  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 36  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 40  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 44  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 50  ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 100 ~/GAP/GAP-kron/GAP-kron_sources.mtx 
