#!/bin/sh

# Looking for delta

# road:  100000 or more
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 10000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 20000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 30000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 40000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 50000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 60000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 70000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 80000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 90000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 100000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 110000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-road/GAP-road.grb 120000 /raid/hyper/gapbs/GAP/GAP-road/GAP-road_sources.mtx 

# kron: 27
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 20 /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 30 /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 40 /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 50 /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 60 /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron.grb 70 /raid/hyper/gapbs/GAP/GAP-kron/GAP-kron_sources.mtx


# twitter: 51
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter.grb 30 /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter.grb 40 /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter.grb 50 /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter.grb 60 /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter.grb 70 /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter.grb 80 /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter.grb 90 /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter.grb 100 /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter.grb 110 /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter.grb 120 /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter.grb 130 /raid/hyper/gapbs/GAP/GAP-twitter/GAP-twitter_sources.mtx

# urand: 35
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 30 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 40 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 50 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 60 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 70 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 80 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 90 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 100 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 110 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 120 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 130 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand.grb 140 /raid/hyper/gapbs/GAP/GAP-urand/GAP-urand_sources.mtx

# web: 150 or 200
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-web/GAP-web.grb 100 /raid/hyper/gapbs/GAP/GAP-web/GAP-web_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-web/GAP-web.grb 150 /raid/hyper/gapbs/GAP/GAP-web/GAP-web_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-web/GAP-web.grb 200 /raid/hyper/gapbs/GAP/GAP-web/GAP-web_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-web/GAP-web.grb 300 /raid/hyper/gapbs/GAP/GAP-web/GAP-web_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-web/GAP-web.grb 400 /raid/hyper/gapbs/GAP/GAP-web/GAP-web_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-web/GAP-web.grb 500 /raid/hyper/gapbs/GAP/GAP-web/GAP-web_sources.mtx 
./build/sssp_test /raid/hyper/gapbs/GAP/GAP-web/GAP-web.grb 600 /raid/hyper/gapbs/GAP/GAP-web/GAP-web_sources.mtx 


