#!/bin/bash

# run all GAP benchmarks

cd BreadthFirstSearch
./do_gap

cd ../BetweennessCentrality
./do_gap

cd ../ConnectedComponents
./do_gap

cd ../PageRank
./do_gap

cd ../SingleSourceShortestPath
./do_gap

cd ../TriangleCount
./do_gap

