#!/bin/sh

./build/gap_tc_test ~/DIMACS10/kron_g500-logn16/kron_g500-logn16.mtx
./build/gap_tc_test ~/DIMACS10/kron_g500-logn17/kron_g500-logn17.mtx
./build/gap_tc_test ~/DIMACS10/kron_g500-logn18/kron_g500-logn18.mtx
./build/gap_tc_test ~/DIMACS10/kron_g500-logn19/kron_g500-logn19.mtx
./build/gap_tc_test ~/DIMACS10/kron_g500-logn20/kron_g500-logn20.mtx
./build/gap_tc_test ~/DIMACS10/kron_g500-logn21/kron_g500-logn21.mtx
./build/gap_tc_test ~/GAP/GAP-kron/GAP-kron.grb

