#!/bin/sh
build/bc_gap_test ~/GAP/GAP-web/GAP-web.mtx ~/GAP/GAP-web/GAP-web_sources.mtx

build/bc_gap_test ~/GAP/GAP-kron/GAP-kron.mtx ~/GAP/GAP-kron/GAP-kron_sources.mtx
build/bc_gap_test ~/GAP/GAP-twitter/GAP-twitter.mtx ~/GAP/GAP-twitter/GAP-twitter_sources.mtx
build/bc_gap_test ~/GAP/GAP-urand/GAP-urand.mtx ~/GAP/GAP-urand/GAP-urand_sources.mtx
build/bc_gap_test ~/GAP/GAP-road/GAP-road.mtx ~/GAP/GAP-road/GAP-road_sources.mtx

