#!/bin/sh

# Looking for delta

# kron: 27
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 20 ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 25 ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 30 ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 35 ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 40 ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 50 ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 60 ~/GAP/GAP-kron/GAP-kron_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-kron/GAP-kron.grb 70 ~/GAP/GAP-kron/GAP-kron_sources.mtx


# twitter: 51
./build/gap_sssp_test ~/GAP/GAP-twitter/GAP-twitter.grb 30 ~/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-twitter/GAP-twitter.grb 40 ~/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-twitter/GAP-twitter.grb 50 ~/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-twitter/GAP-twitter.grb 60 ~/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-twitter/GAP-twitter.grb 70 ~/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-twitter/GAP-twitter.grb 80 ~/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-twitter/GAP-twitter.grb 90 ~/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-twitter/GAP-twitter.grb 100 ~/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-twitter/GAP-twitter.grb 110 ~/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-twitter/GAP-twitter.grb 120 ~/GAP/GAP-twitter/GAP-twitter_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-twitter/GAP-twitter.grb 130 ~/GAP/GAP-twitter/GAP-twitter_sources.mtx

# urand: 35
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 20 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 30 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 40 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 50 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 60 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 70 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 80 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 90 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 100 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 110 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 120 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 130 ~/GAP/GAP-urand/GAP-urand_sources.mtx
./build/gap_sssp_test ~/GAP/GAP-urand/GAP-urand.grb 140 ~/GAP/GAP-urand/GAP-urand_sources.mtx

# web: 150 or 200
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 20 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 30 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 40 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 50 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 70 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 80 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 90 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 100 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 110 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 120 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 130 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 140 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 150 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 200 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 300 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 400 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 500 ~/GAP/GAP-web/GAP-web_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-web/GAP-web.grb 600 ~/GAP/GAP-web/GAP-web_sources.mtx 



# road:  100000 or more
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 10000 ~/GAP/GAP-road/GAP-road_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 20000 ~/GAP/GAP-road/GAP-road_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 30000 ~/GAP/GAP-road/GAP-road_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 40000 ~/GAP/GAP-road/GAP-road_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 50000 ~/GAP/GAP-road/GAP-road_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 60000 ~/GAP/GAP-road/GAP-road_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 70000 ~/GAP/GAP-road/GAP-road_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 80000 ~/GAP/GAP-road/GAP-road_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 90000 ~/GAP/GAP-road/GAP-road_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 100000 ~/GAP/GAP-road/GAP-road_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 110000 ~/GAP/GAP-road/GAP-road_sources.mtx 
./build/gap_sssp_test ~/GAP/GAP-road/GAP-road.grb 120000 ~/GAP/GAP-road/GAP-road_sources.mtx 
